[features]
seeds = false
skip-lint = false
[programs.localnet]
remitano_project = "Cb95wqzowAjpuRi2yRoo9agiko6c5g3eTAWammsWwC1h"

[programs.devnet]
remitano_project = "Cb95wqzowAjpuRi2yRoo9agiko6c5g3eTAWammsWwC1h"

[programs.testnet]
remitano_project = "Cb95wqzowAjpuRi2yRoo9agiko6c5g3eTAWammsWwC1h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/chungquantin/snf-1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
